name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzg3NmIyZWYtODE2OC00YmRkLTg0NGItZGNjYTg4MmUxM2QxIiwidGVuYW50X2lkIjoiZGU2N2Y3ZjQ5OTVmNzkyMmJiNDhiNGU3YzE0MmMzMGMxNzBlMDY2YjNjYWMzMDYzNDE1NGY0ZThkZDQyYjlhNSIsImludGVybmFsX3NlY3JldCI6Ijg3NzlkMzU2LTVjZWYtNDA1NS1iMjQ2LTJkZmE3N2NjMzAyMSJ9.7ie-_nxKZuudUhv7zXtI5t1WiDTxggt1ErUky0rOArA"
JWT_SECRET=	"mysecretkey"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"